### ISSUE TITLE
URLs checklist

### ISSUE THREAD

**Issue by bigfoot90** [phanan/kupo#15]
**This is a fantastic tool!**

Some times the new site is just a modern replacement for an old-style site.
In this cases it is useful to check that all old URLs are properly redirected (301) to a new valid location.

Allow to check multiple URLs *(by uploading a file, or a `<textarea>`)*

Every Url **MUST**:
* Return status code **2xx** or **3xx**
* If returns **301** or **302**, then the destination url **must** be validated too *(if the destination domain is equal to the tested one)*
* The redirect's destination cannot be same as the source

Extra check:
* Non-existent urls **must** return status code **404**, and possibly don't be blank.
  *If a page has less than 60 characters, it can be considered blank.*

**Comment by barryvdh** [comment]
FYI, the 200/404 checks are implemented here: https://github.com/phanan/kupo/pull/7
Not sure about the following of the redirects though, but I think that's probably the default behaviour.

**Comment by bigfoot90** [comment]
Wonderful! I have'nt tryed it jet, but I will do as soon as possible in the next days.

So it is only missing the `<textarea>` where I can put all my links and test they all together.

About the **404**:
As I can see, your class does not checking if a page has some content or is blank.
This is **NOT** a required step *(but should be marked as warning)*, but I known that form many servers as *NGINX* or *Apache* the detault `Not Foud` page is an ugly white page, and this is obviously **NOT SEO Friendly**

**Comment by barryvdh** [comment]
Why is it not SEO friendly? I think search engines ignore 404 pages, as you don't want random invalid pages indexed..
I do agree it's not the most user friendly though.

**Comment by bigfoot90** [comment]
Yes, User friendly. sorry.

**Comment by phanan** [comment]
I think the 30x redirection checking feature is too specific and well beyond the scope of this tool. Isn't there any (SEO) tool out there that can handle this for us?

**Comment by barryvdh** [comment]
Something like https://github.com/spatie/http-status-check ?

**Comment by phanan** [comment]
Closing this issue, for the reasons stated above.
