### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by encodia** [phanan/kupo#23]
Hi there,

is there any chance to use it on nginx?

Thank you

**Comment by phanan** [comment]
It's just a PHP application, you can use it however you like.

**Comment by encodia** [comment]
Thank you Phanan, I'll look for the right rewrite rules.

**Comment by barryvdh** [comment]
It's just Laravel, see for example https://www.digitalocean.com/community/tutorials/how-to-install-laravel-with-an-nginx-web-server-on-ubuntu-14-04
