### ISSUE TITLE
LetsValidate?

### ISSUE THREAD

**Issue by m1guelpf** [phanan/kupo#29]
Is this site using Kupo? It seems like.
https://www.letsvalidate.com

**Comment by hbakhtiyor** [comment]
Yeah

**Comment by barryvdh** [comment]
Yeah, missing the latest pull requests though ;)

Not sure if this is from @phanan but guess not, as it doesn't link back to this repo.

But the licence from Kupo is MIT, so not required to link and/or attribute, other then keeping the existing licence; https://choosealicense.com/licenses/mit/

**Comment by phanan** [comment]
What @barryvdh said.
