### ISSUE TITLE
Undefined property: DOMDocument::$documentElement  in symfony/dom-crawler

### ISSUE THREAD

**Issue by retrogradeMT** [phanan/kupo#31]
Not a bug, but a question.   When installing on a Ubuntu 14.04 /Nginx with php7,  I am getting an error when entering a site in the checker: 
    
    (1/1) ErrorException
    Undefined property: DOMDocument::$documentElement

the error is occuring in vendor/symfony/dom-crawler/Crawler.php', 277

dom-crawler is up to date, symfony/polyfill-mbstring and symfondy/css-selector have been installed.    php-xml and libxml2 have also been installed. 

Any idea what I could be missing?

**Comment by Ethiel97** [comment]
is that answer the solution ? I'm facing the same issue mentioned above.

**Comment by MarvinKlar** [comment]
In my case the dom extension was enabled twice. Once in the `dom.ini` and also in the `php.ini`. I removed the `extension=dom.so` entry from the php.ini and reloaded the apache2 webserver.

**Comment by asilbalaban** [comment]
> In my case the dom extension was enabled twice. Once in the `dom.ini` and also in the `php.ini`. I removed the `extension=dom.so` entry from the php.ini and reloaded the apache2 webserver.

 after hours of researching this is the correct answer for me

**Comment by NazarSm** [comment]
> In my case the dom extension was enabled twice. Once in the `dom.ini` and also in the `php.ini`. I removed the `extension=dom.so` entry from the php.ini and reloaded the apache2 webserver.

this option worked for me
